### ISSUE TITLE
Competition

### ISSUE THREAD

**Issue by holtwick** [holtwick/briefing#10]
[WhereBy](https://whereby.com) former apper.in

<img width="1662" alt="CleanShot 2020-04-05 at 10 59 47@2x" src="https://user-images.githubusercontent.com/49557/78470840-b6f50a00-772c-11ea-8b24-983ead2631d1.png">

**Comment by eruizpy** [comment]
I did not think to laugh !!, but it is the absolute reality

**Comment by holtwick** [comment]
Hehe, right. 

I'll close this ticket, since it was just thought for collecting ideas in the beginning.

**Comment by holtwick** [comment]
https://www.meetspaceapp.com/

**Comment by holtwick** [comment]
https://room.sh

**Comment by holtwick** [comment]
List continued at https://github.com/holtwick/briefing/wiki/Useful-Resources-for-Development#similar-projects
