### ISSUE TITLE
Changing camera on certain Android devices does not work

### ISSUE THREAD

**Issue by holtwick** [holtwick/briefing#102]
Probably related to MediaTracks not being stopped.

Is working here: https://stage.viidoo.chat/test/test-media

**Comment by holtwick** [comment]
Also experiencing issues in Firefox M1 macOS

**Comment by manhere** [comment]
After studying for a long time,  I finally found a solution -> #131 
Probably the same problem:
#32 
#33 
hope it works :)

**Comment by holtwick** [comment]
@manhere thanks for investing so much time into solving this problem. Very much appreciated! It is now live on brie.fi/ng for being tested.
