### ISSUE TITLE
Briefing deployment on private hardware fails with provided configuration steps

### ISSUE THREAD

**Issue by regmibijay** [holtwick/briefing#106]
I cloned the latest version from github and changed the `.env` as per recommendation. I adjusted the `ROOM_PATH` in `service-worker.js` from `/ng/` to `/briefing/` , then I ran `npm run build` in `/app` and deployed the content from the `/dist` to `/briefing`. I was hit with `404` as `/briefing/index.html` was requesting `css` and `js` files were being requested from `server.domain/js/` etc. I had to change `publicPath` to `/briefing` in `vue.confing.js`  for briefing to get loaded properly. Now when I load `index.html` , I can create a room, enter it, but when I open the room link, that link is reported as not found by the server. Am I missing something in the configuration?

Same issue persists when running `npm run serve`.

OS: Raspian Linux RPi4 5.10.17
Webserver:   nginx/1.14.2
NPM: 7.9.0
Node.js: v10.24.0
Vue-CLI-Service: 4.5.12

**Comment by holtwick** [comment]
`ROOM_PATH` only describes the sub-path to the room. If you want to move the whole project into a sub-folder, you need to adjust this line as well: https://github.com/holtwick/briefing/blob/master/app/vue.config.js#L14

You might need to play a bit, to get the right config working then.
