### ISSUE TITLE
App isnt working

### ISSUE THREAD

**Issue by aarush-paul** [holtwick/briefing#112]
Hello,
Having difficulties to connect. So I created room, shared link with my friend and when he joined we can see ourselves but not each other, the sign "waiting for connection" instead of partner's video. We tried Firefox and chrome, both are latest version. Also mobile chrome on latest android. Same thing. Both computers are windows systems. What could be a problem. Is there any firewall rules or router setting should be changed?
Thank you.

**Comment by holtwick** [comment]
This sounds indeed like a firewall issue. Some services are called on different ports than usual web ports.

**Comment by aarush-paul** [comment]
Ohh, so can you suggest me ways on how should I fix it?
Coz I also believe it's some problem at my end because 8 also tried other Luke mirotalksfu, mirotalk, camus etc
