### ISSUE TITLE
Someone is infringing on your project

### ISSUE THREAD

**Issue by ruralcoder** [holtwick/briefing#114]
Found this youtube video that talks about building a zoom clone, but points to their own website full of ads. The github link and live demo point to this project

https://www.youtube.com/watch?v=x1U_9h-tMJg

https://codingshiksha.com/vue/vue-js-zoom-clone-group-video-chat-using-node-js-socket-io-webrtc-and-socket-io-full-project-for-beginners/

**Comment by holtwick** [comment]
Thanks for pointing me to this strange video presentation. I added a comment to the video pointing back to my project. I think there is not much more I can do right now, without wasting time ;)

**Comment by holtwick** [comment]
Ok, the guy delete my comment immediately. I'll contact YouTube.

**Comment by ruralcoder** [comment]
I did report him to YouTube as well! Twice now!!! Let's see.

**Comment by holtwick** [comment]
Well at least at the following page he gives the correct link. I think there is not much more to do. I'll therefore close the ticket. Thanks again for the support @ruralcoder
