### ISSUE TITLE
Browser freeze when sharing screen with multiple users (3+) following the meeting

### ISSUE THREAD

**Issue by ikigai-festuccia-simone** [holtwick/briefing#115]
Hi, I've noticed that the browser (but sometimes also the entire OS) get frozen when I switch from camera to screen share.

usually happens when 3 or more people are partecipating the meeting

**Comment by holtwick** [comment]
Thanks. Could you please provide more details like OS name and version, browser name and version? Thanks.

**Comment by ikigai-festuccia-simone** [comment]
OS: Windows 10 Pro build 19043.1466
Browser: Chrome 97.0.4692.99
3 screen configuration 

it happens when multiple people are listening (3 or 4) everything it's ok for a while but after 1 minutes every tab of chrome freeze, and then system became unstable

**Comment by holtwick** [comment]
Is the device powerful, i.e. enough CPU power and memory? Is the overall system still responsive or does it consume too much CPU?

**Comment by ikigai-festuccia-simone** [comment]
device is a ryzen5 1600 with 16GB ram, OS is running on a SSD,

i'll try to crash again and see if it goes out of ram, or if CPU goes 100% and update the issue.
