### ISSUE TITLE
net::ERR_SSL_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by JorisNijkamp1** [holtwick/briefing#116]
I am getting an error because of SSL protocol.

Can someone help me?

**Comment by holtwick** [comment]
Is this working for you now?

**Comment by JorisNijkamp1** [comment]
Yes it is but now I'm having a different error... State.stream does not get filled so my app-video doesn't load.. can you help?

**Comment by holtwick** [comment]
Ok. 

If the original app works, I cannot help with custom installs. Sorry, I just don't have the time for that :(

**Comment by JorisNijkamp1** [comment]
It is the original app
