### ISSUE TITLE
I am having issues that state.stream doesnt get filled.

### ISSUE THREAD

**Issue by JorisNijkamp1** [holtwick/briefing#117]
Can some help me with state.stream. It doesnt get filled with values so i dont see myself in the camera

**Comment by holtwick** [comment]
Please nite that modern browsers only allow video access on HTTPS domains or localhost.

**Comment by JorisNijkamp1** [comment]
I'm running it in localhost. So I don't think that is the problem.

That state.stream just doesn't get filled I don't know why.

**Comment by holtwick** [comment]
I think I was able to address the issue in this branch: https://github.com/holtwick/briefing/tree/develop

**Comment by holtwick** [comment]
This is now solved with Briefing 2.0
