### ISSUE TITLE
Error message when using an iFrame; DOMException: Failed to register a ServiceWorker

### ISSUE THREAD

**Issue by gardnerinfotech** [holtwick/briefing#120]
Although it continues to work, users sometimes witness a bright red error message on the screen when launching video in an iFrame. This appears to be exactly the same symptoms as a fixed issue that appears on a very similar project, Jitsi Meet: https://github.com/jitsi/jitsi-meet/issues/9712

**Comment by holtwick** [comment]
I'm currently modernizing the code on https://github.com/holtwick/briefing/tree/develop Service Worker has been removed and the problem should hopefully not show up anymore in future versions. Thanks for the hints!

**Comment by holtwick** [comment]
Fixed in Briefing 2.0. See https://holtwick.de/chat.html for demonstration.
