### ISSUE TITLE
Killerfeatures ;)

### ISSUE THREAD

**Issue by holtwick** [holtwick/briefing#14]
- [x] - Blur background #17 
- [ ] - Emojis #11 
- [ ] - Movie like effects, like freezing frames and titles
- [ ] - Audio transcriptions
- [ ] - 3D masks
- [ ] - Other filters like painting like etc.
- [ ] - Drag and drop media like images, audio, video; playback synchronous on all devices
- [ ] - https://giphy.com/
- [ ] - Whiteboard ([ExcaliDraw](https://github.com/excalidraw/excalidraw))

**Comment by moqmar** [comment]
Will this be optional? I really like the current simplicity of it (which I think is a real killer feature, especially in comparison to other tools like this), I'd love if stuff like this was completely optional on a per-room basis.

**Comment by holtwick** [comment]
This is just a collection of random ideas I wrote down before releasing the software. If I ever add some of these they will very likely be optional. E.g. blurring is lazily loaded only when activated.

**Comment by holtwick** [comment]
- [  ] Transcription / Speech Recognition - OFFLINE! https://developer.mozilla.org/en-US/docs/Web/API/Web_Speech_API

**Comment by image72** [comment]
audio, video record
