### ISSUE TITLE
Docker Image File Source Error

### ISSUE THREAD

**Issue by tctlrd** [holtwick/briefing#146]
I am not able to use the docker image due to the following error:
GET https://data.holtwick.de/js/plausible.js net::ERR_BLOCKED_BY_CLIENT

It seems that this line is the issue:
https://github.com/holtwick/briefing/blob/master/index.html#L37

**Comment by d-k-bo** [comment]
I think it very problematic (both from an ethical and a legal standpoint) that a self-hosted solution tries to embed third-party tracking. It is not great to rely on the browser to block the request based on the CSP.

**Comment by holtwick** [comment]
You are absolutely right, I left it there by mistake. Will update quickly. Thanks for the info.

**Comment by holtwick** [comment]
I uploaded a new docker image at https://hub.docker.com/r/holtwick/briefing

I hope I didn't miss anything. Just in case I missed something, please leave a note here. I'll fix it then. Thanks.

**Comment by tctlrd** [comment]
Thank you Dirk.
