### ISSUE TITLE
Zoom on face(s)

### ISSUE THREAD

**Issue by holtwick** [holtwick/briefing#20]
Scale and position the video in a way that the face is placed perfectly on the viewport

**Comment by moqmar** [comment]
I'd also like to disable the zoom completely and get black bars around the image instead, especially for screen sharing. Maybe it could be done similarly like I think Wire did, where you can double-click on the camera to zoom in and out (and thus remove/show the black bars)?

**Comment by holtwick** [comment]
I agree. Some more visual representations of the videos should be added. Contributions are welcome ;)

**Comment by holtwick** [comment]
https://github.com/justadudewhohacks/face-api.js

**Comment by holtwick** [comment]
> I'd also like to disable the zoom completely and get black bars around the image instead, especially for screen sharing. Maybe it could be done similarly like I think Wire did, where you can double-click on the camera to zoom in and out (and thus remove/show the black bars)?

This has been implemented.

Just saw your fork. That's awesome. Like the Dockerfile etc.
