### ISSUE TITLE
blue screen in firefox

### ISSUE THREAD

**Issue by 0163someone** [holtwick/briefing#30]
just opened brie.fi/ng with firefox and ended up in a blue screen. but this has nothing to do with brie.fi/ng but witt my damn firefox installation. maybe someone knows why...

**Comment by holtwick** [comment]
@0163someone  Which operating system? Does it crash immediately after opening the page?

**Comment by 0163someone** [comment]
Win8 and latest FF. Crash in the very second the cam was activated. but never mind - mein Computer is "schwul" :dagger:

**Comment by holtwick** [comment]
Turning off the hardware acceleration in FF should fix the problem.
