### ISSUE TITLE
Can't switch between video sources

### ISSUE THREAD

**Issue by huzaifahj** [holtwick/briefing#32]
Hey!

Thanks for making your work open source. Happy to contribute to turn servers in future.

So I've noticed that on mobile I can't switch between sources as shown in the screenshot below. Only the front camera works. Phone is Huawei P20 Pro

[Screenshot](https://imgur.com/a/xIM7Lel)

**Comment by holtwick** [comment]
Thanks for the report. Which browser do you use? Might there be trouble with some access rights for the mentioned cameras?
