### ISSUE TITLE
Switching between video and screenshare

### ISSUE THREAD

**Issue by ericsrp** [holtwick/briefing#33]
Hello buddy. first of all congrats about yout project.
im testing it in https://brie.fi/ng in computer (windows + chrome) and its ok with video and audio. but when i switch from camera to screenshare my audio deaseper and then when i return to camera then the audio goes back..

by the way when we in computer, and the screen is sharing then the screen is  cropped..

**Comment by holtwick** [comment]
The cropping is intentional for now. See #7 

I'll look into the bug you described. Thanks.

**Comment by holtwick** [comment]
I updated audio handling, please try again @ericsrp . Thanks

**Comment by ericsrp** [comment]
thanks buddy. please let me know. do you available to hire to a dev job? how can i contact you?

**Comment by holtwick** [comment]
You can contact me via email. Here the contacts https://holtwick.de/imprint
