### ISSUE TITLE
Moderated Conference

### ISSUE THREAD

**Issue by holtwick** [holtwick/briefing#34]
In certain scenarios like virtual classes, it is useful to have a moderator that manages when participants should talk or not. 

First of all it would be useful to give a hand sign, when somebody wants to speak but not disturb others that are still speaking like raising the hand in the class. See Jitsi or #11 

Then the moderator should be able to mute everybody but the speaker and himself. See Jitsi "Mute everybody else". But the moderator should also be able to unmute people. Every participant that has been muted by somebody else should receive a message like "Person A moved on stage by Person B" and should be able to unmute himself any time.

For common questions it should be possible to do a quick poll as well, the simplest would be "thumb up" or "down". Or undecided. Or starring between 1 to 5 stars. Or multiple choice. Lend some inspirations by BigBlueButton

**Comment by eruizpy** [comment]
I did not think to laugh !!, but it is the absolute reality
