### ISSUE TITLE
Install how to

### ISSUE THREAD

**Issue by nikpakar** [holtwick/briefing#37]
Very nice work. Clean and simple.

Im trying to build the client and get it working but experiencing problems. Built and run as
serve dist, but cannot get to the web folder neither a room with direct /roomname. If i run from web folder then only the home page comes up.

Is there any simple how to install guide. If i have succeeded would hv done one.

thanks again for the very nice project.

**Comment by holtwick** [comment]
The magic happens in the `.htaccess` file for Apache: https://github.com/holtwick/briefing/blob/master/web/.htaccess

But you can also better use the PWA distribution. Start with `npm run pwa:serve` and `npm run pwa:build` for distribution under `ngs` folder: https://github.com/holtwick/briefing/blob/master/package.json#L24 

You should adopt the settings for your needs of just use https://brie.fi/ng directly.

**Comment by nikpakar** [comment]
Thank you so much for the guide. managed to work around the .htaccess.

But still it seems /app/index.html not seems executing to dist folder. Just giving url not found when rewrite happens with the room name.

**Comment by holtwick** [comment]
The folder is `/ngs`. See this setting https://github.com/holtwick/briefing/blob/master/vue.config.js#L40

**Comment by nikpakar** [comment]
Thanks again and sorry for the trouble. It doesnt even mount to /ngs. simply says not found when re-write occurred. .htaccess is working fine and all 3 rules works properly. when the last rule /ng/roomid attempt to rewrite it cant find the mount point

**Comment by nikpakar** [comment]
Sorry for been blind, after much effort found out my error. and now managed to get the PWA up and running directly on my root folder. On PWA whats the format of the join in url as it seems its not appending to the home url like in /ng

**Comment by holtwick** [comment]
The new code is online. No more hacking required. All is a PWA now and a simple .htaccess example is also available here https://github.com/holtwick/briefing/blob/master/public/.htaccess#L23
