### ISSUE TITLE
Notifications on incoming calls

### ISSUE THREAD

**Issue by holtwick** [holtwick/briefing#43]
Use PWA notification features: https://developer.mozilla.org/de/docs/Web/API/PushManager

Extend signal server to handle these.

**Comment by nikpakar** [comment]
Are we going to implement one to one calling feature ?

**Comment by holtwick** [comment]
Yeah, subscribers could get a notification when somebody enters a room and then join directly. That's at least the idea.

**Comment by holtwick** [comment]
The feature is implemented and waiting for testing and signal server update.

**Comment by holtwick** [comment]
Will come as an option in Briefing 4.0
