### ISSUE TITLE
PWA - Camera still in use after disconnecting from the room

### ISSUE THREAD

**Issue by nikpakar** [holtwick/briefing#44]
In PWA (/ngs) after disconnecting from the room, camera shown as still active and been used until the page is manually reloaded.

On /ng this doesnt happen since http re-writes reload it to a new page.

Attached screenshot shows the camera is still active after disconnected.

**Comment by nikpakar** [comment]
<img width="1280" alt="Screenshot 2020-05-16 at 22 17 52" src="https://user-images.githubusercontent.com/63545958/82125423-7f658d00-97c3-11ea-818d-08a04a5553e6.png">

**Comment by holtwick** [comment]
This should work if you press the hangup button.

I leave this open because navigating back should also force a reload of the page to hang up and end any open media channels.

**Comment by nikpakar** [comment]
This is infact after pressing hangup and return to this screen.

**Comment by holtwick** [comment]
On Safari? Please try again, I cannot reproduce this issue any more. Thanks.

**Comment by nikpakar** [comment]
Yes on safari. Now its gone. Perfectly fine on both ng and ngs.

Thanks
