### ISSUE TITLE
how to build in nginx?

### ISSUE THREAD

**Issue by HoldSkill** [holtwick/briefing#45]

**Comment by holtwick** [comment]
Briefing is a static website. No special requirements.

**Comment by HoldSkill** [comment]
location ~* \service-worker.(js)$ {
        expires 0;
        add_header Cache-Control "max-age=0";
        add_header Content-Type "text/javascript; charset=utf-8";
    }  
    
    rewrite ^/$ /ng/ permanent;
    rewrite ^/ngs?/?$ /index.html;
    rewrite ^/ngs?/(.+?)$ /index.html;

**Comment by holtwick** [comment]
Good to know, thanks!
