### ISSUE TITLE
Camera and Audio device not showing

### ISSUE THREAD

**Issue by AmandaDLyon** [holtwick/briefing#47]
I tried running Ionic Capacitor on your platform and for some reason, it does not show the Camera and Audio options. The buttons are working (sort of) but the names of the hardware arent shown.

It works just fine on PWA. Could you please help me out here?
![Screenshot](https://user-images.githubusercontent.com/65491209/83329741-ce71ee80-a2a8-11ea-9bce-34d2caa24918.jpeg)

**Comment by holtwick** [comment]
Hi @AmandaDLyon This is the place where the device names are prepared for the UI: https://github.com/holtwick/briefing/blob/master/app/src/components/app-settings.vue#L49 Please try to add some logging. 

Here is the place where the information is actually collected: https://github.com/holtwick/briefing/blob/master/app/src/logic/stream.js#L3

You might also want to call the device enumeration directly and see if the data is correct in the first place:

```
navigator.mediaDevices.enumerateDevices().then(devices => {
  console.log(devices)
})
```

If you find the reason it would be great if you could provide a fix. Thanks!

**Comment by AmandaDLyon** [comment]
According to Android Studio's LogCat, the cameras are recognised and there are no errors there. It's just there's nothing to output it in the front-end. That's my guess as of now. I'll try to dig in deeper.

**Comment by holtwick** [comment]
The screenshot also shows that something has been found, just the `.label` info is missing or not displayed. You should probably dig a little bit deeper there. 

Sometimes Vue.js is the problem. Cloning objects before adding them to e.g. `state` object via `JSON.parse(JSON.stringify(value))` sometimes helps.

**Comment by AmandaDLyon** [comment]
Even I feel that this issue could be caused by Vue since there are literally no errors in Android Logs. 

Infact, take a look at one of the Android Log Statements:

```
 1713-2629/? I/CameraService: CameraService::connect call (PID -1 "com.webrtc.app", camera ID 1) for HAL version default and Camera API version 2

 1713-2629/? I/Camera2ClientBase: Camera 1: Opened. Client: com.webrtc.app (PID 6035, UID 10085)

 1713-2629/? I/CameraDeviceClient: CameraDeviceClient 1: Opened
```


The Only errors I see are:

``` 
E/libc: Access denied finding property "ro.camera.req.fmq.size"
E/libc: Access denied finding property "ro.camera.res.fmq.size"
E/Camera3-Device: configureStreams: Stream 0: DataSpace override not allowed for format 0x23
```

And from what I have read, these errors have pretty much nothing to do with what we are trying to fix.

Could you maybe elaborate a little on what you said and maybe attempt this fix, or tell me where I can add what. I am kinda new to Vue so I am going to need all the help I can get ;)



> The screenshot also shows that something has been found, just the `.label` info is missing or not displayed. You should probably dig a little bit deeper there.
> 
> Sometimes Vue.js is the problem. Cloning objects before adding them to e.g. `state` object via `JSON.parse(JSON.stringify(value))` sometimes helps.

**Comment by AmandaDLyon** [comment]
After a trying various ways to get the platform to work, I can confirm that this is an issue caused by vue and not by Capacitor/Cordova.

I need @holtwick you to help me out here. Maybe attempt implementing what you suggested. Maybe that might just work...

**Comment by holtwick** [comment]
@AmandaDLyon I changed it a bit, hope it works now

**Comment by plmercereau** [comment]
Hi @AmandaDLyon, I'm curious to know if you solved your problem, and how. I have the very same issue with quasar/vue, and although it works fine when running `navigator.mediaDevices.enumerateDevices` on web mode, labels are still empty when running on capacitor...
Many thanks
