### ISSUE TITLE
Participant names

### ISSUE THREAD

**Issue by daneden** [holtwick/briefing#49]
I just discovered briefing (I was about to embark on a pretty much identical product) and really love it! One thing that would be great is the ability to set a screen name. This would be particularly helpful for group chats where people have their video turned off but still be able to identify who’s talking.

**Comment by holtwick** [comment]
Hi @daneden that's a good point. I'm going to look into it.

**Comment by holtwick** [comment]
The name you set in the text chat is also displayed in the video. I'll improve this feature, but it is a start ;)
