### ISSUE TITLE
Bad Picture Quality with Webcam on Surface Go

### ISSUE THREAD

**Issue by christophtill** [holtwick/briefing#64]
![briefing-pic-quality](https://user-images.githubusercontent.com/67745514/86953257-773b2580-c154-11ea-9298-f32d9670d871.png)

The picture quality is bad on the Microsoft Surface Go using the internal webcam. It doesn't matter, which Browser I use or if I use the Briefing-PWA App. The picture comes out with low resolution and a lot of artefacts. It's not a matter of the cam, as other video conferencing service provide a much better picture quality. If I use another device like my smartphone, the picture quality is better than using the Surface Go. 

Here's an example using fairmeeting:

![2020-07-08 19 54 13 fairmeeting net 472daaed0b62](https://user-images.githubusercontent.com/67745514/86953569-e87ad880-c154-11ea-868d-8d9b09494e28.jpg)

**Comment by Slender1808** [comment]
what codecs are used by default ?

**Comment by holtwick** [comment]
Overall the default settings are used, no special codecs enforced. Help appreciated.

**Comment by christophtill** [comment]
I today tried it again and it seems like that Briefing thinks, that I have a bad connection, because sometimes the image quality is really good, but then it turns bad. So it's no issue with the camera but it seems to be an issue of bandwidth and the mesurement of it.

**Comment by christophtill** [comment]
Here are two screenshots, that might help reproduce the problem. I tried it with different light situations and this definitely has an effect on the resolution, that's used. 

![2020-09-09 14 28 32 brie fi 76a470b308eb](https://user-images.githubusercontent.com/67745514/92598484-2ad1aa80-f2a9-11ea-9e58-d2f40a3a57e7.jpg)
![2020-09-09 14 29 02 brie fi af4616e96022](https://user-images.githubusercontent.com/67745514/92598495-2efdc800-f2a9-11ea-95de-a891e5308827.jpg)

I don't know if it is a light / dark issue ...but it has to do something with light.

**Comment by christophtill** [comment]
It seems, that the problem is solved. During the last days, I didn't have the issue. Maybe Microsoft changed something... Or did you? It's now even in low light a good solution picture.

**Comment by holtwick** [comment]
I did not change anything ;) Good to know it now works better. Thanks!
