### ISSUE TITLE
Briefing doesn't work correctly on older iPad

### ISSUE THREAD

**Issue by christophtill** [holtwick/briefing#65]
I had a videochat with a friend. He used an iPad for connecting and used the safari-browser (he couldn't find out which version). The iPad uses iOS 12.4.5 and it's an iPad Air. The issue was, that I was able to see him and me, but he was only seeing his image, but couldn't see me. It seemed like my webcam was turned off for him although I had turned it on.

**Comment by holtwick** [comment]
Thanks for letting me know. Camera support and WebRTC streams seem to be pretty new to Safari.
