### ISSUE TITLE
Green light remains on when video is turned off

### ISSUE THREAD

**Issue by abhishekgahlot** [holtwick/briefing#67]
Hi @holtwick ,

The project is really great, works well. Although the green light on camera remains on when the video is turned off from UI.

I have previously worked off with Video Infrastructure so I know the solution to this problem. I can take this task and raise PR.

BTW Have you thought of moving the project into a separate open-source organization? It looks like a great initiative.

**Comment by holtwick** [comment]
Any help would be great! Looking forward to your PR.

An organization named `briefing`? Would that have any advantages? If you like to I would like to hear your opinion on it as well.

Thanks a lot!

**Comment by holtwick** [comment]
Is this still an issue?
