### ISSUE TITLE
error 404 not found if i go directly to the room url 

### ISSUE THREAD

**Issue by MudrekaBohra** [holtwick/briefing#68]
Firstly Thank you for the clean and slim project
i managed to get the pwa working on both apache and nginx and on both if i visit the website as the normal url without /ng/room it works but if i goto the complete url at once  like https://url/ng/room it gives me 404 on apache and 502 bad gateway on nginx but 
Note: if i visit the website as https://url first on the device and then if  i go to the room url directly it works but if a browser or device has not visited the PWA before and directly goes to the room page it gives the above mentioned error
Thank you

**Comment by holtwick** [comment]
I added a sample `.haccess` for Apache as inspiraton https://github.com/holtwick/briefing/wiki/Apache-Configuration
