### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by albanobattistella** [holtwick/briefing#73]
Ciao Dirk,
on briefing not at all italian translation appear.
more or less half in english and half in italian.

**Comment by holtwick** [comment]
@albanobattistella please try again now, it should be fixed.

**Comment by albanobattistella** [comment]
ok...fixed!

Danke!
________________________________
Da: Dirk Holtwick <notifications@github.com>
Inviato: lunedì 17 agosto 2020 16:07
A: holtwick/briefing <briefing@noreply.github.com>
Cc: albanobattistella <albano_battistella@hotmail.com>; Mention <mention@noreply.github.com>
Oggetto: Re: [holtwick/briefing] Localization (#73)


@albanobattistella<https://github.com/albanobattistella> please try again now, it should be fixed.
