### ISSUE TITLE
Full Screen Button

### ISSUE THREAD

**Issue by christophtill** [holtwick/briefing#78]
Hi everyone,

just something quick, that I discovered, while using Briefing: Some of the people, I get in contact with over this plattform, are always searching for a Fullscreen Button. Could this be implemented?

Greetings, Christoph.

**Comment by holtwick** [comment]
Sure, good idea.

**Comment by holtwick** [comment]
Did implement, will be online soon.

https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API
