### ISSUE TITLE
How to launch?

### ISSUE THREAD

**Issue by AmandaDLyon** [holtwick/briefing#84]
Hey Holtwick, I was wondering how I would put this up on a webserver and run it on top of a domain using NGINX.

I have gotten it to work fine on localhost but whenever I try running it on a server, the browser console spits out 404 errors stating each compiled js and html file is not found.

I have an nginx web-server running reverse proxy on port 8080.

Please help me out here. Cheers!

**Comment by holtwick** [comment]
Hi. You may find details about Apache installation in the wiki https://github.com/holtwick/briefing/wiki

I'm afraid I cannot help much with NGINX. Sorry.

**Comment by AmandaDLyon** [comment]
Could you help me out with Apache? Like where would I edit the htaccess file ?

**Comment by AmandaDLyon** [comment]
I have never used apache and I couldn't quite get my finger on it

**Comment by holtwick** [comment]
Sorry, I cannot give step by step help. 

First of all, you could certainly directly use the brie.fi/ng service.

If you want to install your own interface, various servers are required. Besides the web server you'll need signaling and STUN/TURN. Please look into the wiki documentation for details. Thanks.
