### ISSUE TITLE
"waiting for connection"

### ISSUE THREAD

**Issue by shrisha108** [holtwick/briefing#99]
Hello,
Having difficulties to connect. So I created room, shared link with my friend and when he joined we can see ourselfs but not each other, the sign "waiting for connection" instead of partner's video. We tried firefox and chrome, both are latest version. Also mobile chrome on latest android. Same thing. Both computers are linux systems. What could be a problem. Is there any firewall rules or router setting should be changed?
Thank you.

**Comment by holtwick** [comment]
Does this problem still exist?
